# Generated by Django 5.2.7 on 2025-11-04 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50)),
                ('device_type', models.CharField(choices=[('laptop', 'Laptop'), ('router', 'Router'), ('mobile', 'Mobile'), ('desktop', 'Desktop'), ('other', 'Other')], max_length=50)),
                ('mac_address', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('disconnected', 'Disconnected')], default='active', max_length=50)),
                ('installation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
